import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
    tr: {
        online_order: 'Online Sipariş',
        select_product: 'Ürün Seç',
        write_order: 'Yazarak Sipariş',
        ai_placeholder: 'Siparişinizi buraya yazın... Örn: 2 Mercimek çorbası',
        add_to_list: 'Listeye Ekle',
        cart: 'Sepetiniz',
        delivery_method: 'Teslimat Yöntemi',
        home_delivery: 'Eve Teslimat',
        outside: 'dışı',
        pickup: 'Evden Alacağım',
        your_info: 'Bilgileriniz',
        welcome_user: 'Hoşgeldin',
        full_name: 'Adınız Soyadınız',
        phone_number: 'Telefon Numaranız',
        address: 'Teslimat Adresi',
        order_date: 'Sipariş Tarihi',
        notes: 'Ek Notlar',
        notes_placeholder: 'Alerjiler veya özel istekler...',
        subtotal: 'Ara Toplam',
        delivery_fee: 'Teslimat Ücreti',
        delivery_fee_note: 'Amsterdam içi teslimat €8, Amsterdam dışı €10. Posta kodunuz 10xx veya 11xx ile başlıyorsa Amsterdam içi sayılır.',
        total: 'Toplam',
        confirm_order: 'Siparişi Onayla',
        success_title: 'Siparişiniz Alındı!',
        success_message: 'Mezzesalade\'yi tercih ettiğiniz için teşekkür ederiz.',
        order_summary: 'Sipariş Özeti',
        new_order_btn: 'Yeni Sipariş Oluştur',
        login_msg: 'Önceki siparişlerinizi görmek ve bilgilerinizi otomatik doldurmak için telefon numaranızı girin.',
        login_btn: 'Beni Tanı',
        previous_orders: 'Geçmiş Siparişleriniz',
        no_orders: 'Henüz siparişiniz bulunmuyor.',
        logout: 'Çıkış Yap',
        identifying: 'Kimlik Doğrulanıyor...',
        optional: 'Opsiyonel',
        edit: 'Düzenle',
        update_order: 'Siparişi Güncelle',
        status_new: 'Yeni',
        status_preparing: 'Hazırlanıyor',
        status_ready: 'Hazır',
        status_delivered: 'Teslim Edildi',
        cannot_edit: 'Bu sipariş işleme alındığı için artık düzenlenemez.',
        cancel: 'İptal',
        shortcut_tip: '💡 İpucu: Bu sayfayı telefonunuzun ana ekranına ekleyerek ("Ana Ekrana Ekle") bir uygulama gibi hızlıca sipariş verebilirsiniz.',
        get_directions: 'Yol Tarifi Al',
        pickup_address_title: 'Teslim Alma Adresi',
        date_confirmation_note: 'Not: Seçilen tarih için müsaitlik durumumuzu onaylamak üzere sizinle iletişime geçeceğiz.',
        filter_by_diet: 'Diyete Göre Filtrele',
        diet_v: 'Vegan',
        diet_vg: 'Vegetarian',
        diet_gf: 'Gluten-Free',
        diet_n: 'Kuruyemiş İçerir',
        order_overview: 'Sipariş Özeti',
        confirm_and_send: 'Onayla ve Gönder',
        edit_order: 'Düzenle',
        added_to_cart: 'Sepete eklendi!',
        admin_page: 'Admin Sayfası',
        admin_management: 'Mezzesalade Yönetim',
        ai_order: 'AI Sipariş',
        new_order: 'Yeni Sipariş',
        all_orders: 'Tüm Siparişler',
        revenue_report: 'Ciro Raporu',
        calendar: 'Takvim',
        daily_summary: 'Günlük Özet',
        products: 'Ürünler',
        customers: 'Müşteriler',
        pending_orders: 'Bekleyen Siparişler',
        see_all: 'Tümünü Gör',
        no_pending_orders: 'Bekleyen işlem bulunmuyor',
        notifications: 'Bildirimler',
        no_notifications: 'Yeni bildirim yok',
        items: 'ürün',
        preparing: 'Hazırlanıyor',
        total_revenue: 'Toplam Ciro',
        today_orders: 'Bugünkü Sipariş',
        total_orders: 'Toplam Sipariş',
        active_customers: 'Aktif Müşteri',
        order_details: 'Sipariş Detayı',
        customer_details: 'Müşteri Bilgileri',
        order_status: 'Sipariş Durumu',
        order_date_label: 'Sipariş Tarihi',
        last_updated: 'Son Güncelleme',
        back_to_calendar: 'Takvime Dön',
        daily_summary_title: 'Günlük Özet',
        shopping_list: 'Alışveriş Listesi',
        by_products: 'Ürünlere Göre',
        by_category: 'Kategoriye Göre',
        total_items: 'Toplam Ürün',
        share_report: 'Raporu Paylaş',
        share_menu: 'Menüyü Paylaş',
        delete_confirmation: 'Emin misiniz?',
        save: 'Kaydet',
        update: 'Güncelle',
        days_short: ['Pzt', 'Sal', 'Çar', 'Per', 'Cum', 'Cmt', 'Paz'],
        months: ['Ocak', 'Şubat', 'Mart', 'Nisan', 'Mayıs', 'Haziran', 'Temmuz', 'Ağustos', 'Eylül', 'Ekim', 'Kasım', 'Aralık'],
        whatsapp_import: "WhatsApp'tan Al",
        manual_order: 'Manuel Sipariş',
        product_summary: 'Ürün Özeti',
        printable_summary: 'Yazdırılabilir Özet',
        today: 'Bugün',
        no_order_today: 'Bugün için sipariş yok',
        customer: 'Müşteri',
        recent_orders: 'Son Siparişler',
        all: 'Tümü',
        no_order_date: 'Bu tarihte sipariş yok',
        order: 'Sipariş',
        item: 'Ürün',
        search_placeholder: 'Müşteri veya sipariş ara...',
        date_filter: 'Tarih Filtresi',
        status_filter: 'Durum Filtresi',
        clear_filters: 'Filtreleri Temizle',
        no_orders_found: 'Sipariş bulunamadı',
        date_all: 'Tüm Zamanlar',
        date_today: 'Bugün',
        date_yesterday: 'Dün',
        date_this_week: 'Bu Hafta',
        date_last_week: 'Geçen Hafta',
        date_this_month: 'Bu Ay',
        date_last_month: 'Geçen Ay',
        date_last_3_months: 'Son 3 Ay',
        date_this_year: 'Bu Yıl',
        date_last_year: 'Geçen Yıl',
        date_custom: 'Özel Tarih Aralığı',
        start_date: 'Başlangıç',
        end_date: 'Bitiş',
        more: 'daha...',
        customer_selection: 'Müşteri Seçimi',
        select_customer_btn: 'Müşteri Seç',
        add_new_customer_btn: 'Yeni Müşteri Ekle',
        add_product_btn: 'Ürün Ekle',
        order_items: 'Sipariş İçeriği',
        save_order: 'Siparişi Kaydet',
        no_items_in_order: 'Henüz ürün eklenmedi',
        choose_variation: 'Seçenek Seçin',
        order_summary_title: 'Sipariş Özeti',
        edit_order_title: '✏️ Siparişi Düzenle',
        new_order_title: '📝 Yeni Sipariş',
        change_btn: 'Değiştir',
        delivery_address_label: '📍 Teslimat Adresi',
        address_placeholder: 'Teslimat adresi...',
        select_customer_placeholder: 'Müşteri seçin...',
        new_customer_title: 'Yeni Müşteri',
        name_label: 'İsim',
        phone_label: 'Telefon',
        note_label: 'Not',
        name_placeholder: 'Müşteri adı',
        search_product_placeholder: 'Ürün ara...',
        search_results_title: 'Arama Sonuçları',
        categories_title: 'Kategoriler',
        saving_btn: '⏳ Kaydediliyor...',
        unknown: 'Bilinmeyen',
        revenue_report_title: 'Ciro Raporu',
        today_total_revenue: 'Bugünkü Toplam Ciro',
        compared_to_yesterday: 'Düne göre',
        pending_orders_count: 'Bekleyen Siparişler',
        no_pending_orders: 'Bekleyen sipariş bulunmuyor',
        daily_revenues_title: 'Günlük Cirolar',
        today_label: 'Bugün',
        orders_count: 'sipariş',
        customers_title: '👥 Müşteriler',
        new_btn: '+ Yeni',
        search_customers_placeholder: 'Müşteri ara...',
        no_customers_found: 'Müşteri bulunamadı',
        add_first_customer: '+ İlk Müşteriyi Ekle',
        edit_customer_title: 'Müşteri Düzenle',
        email_label: 'Email',
        email_placeholder: 'ornek@email.com',
        delete_customer_confirm: 'Bu müşteriyi silmek istediğinizden emin misiniz?',
        validation_name_phone: 'İsim ve telefon zorunludur!',
        ai_no_match: 'Eşleşen ürün bulunamadı. Lütfen ürün adlarını kontrol edin.',
    },
    en: {
        online_order: 'Online Order',
        select_product: 'Select Product',
        write_order: 'Order by Text',
        ai_placeholder: 'Write your order here... e.g. 2 Lentil soup',
        add_to_list: 'Add to List',
        cart: 'Your Cart',
        delivery_method: 'Delivery Method',
        home_delivery: 'Home Delivery',
        outside: 'outside',
        pickup: 'Pick up from home',
        your_info: 'Your Information',
        welcome_user: 'Welcome',
        full_name: 'Full Name',
        phone_number: 'Phone Number',
        address: 'Delivery Address',
        order_date: 'Order Date',
        notes: 'Additional Notes',
        notes_placeholder: 'Allergies or special requests...',
        subtotal: 'Subtotal',
        delivery_fee: 'Delivery Fee',
        delivery_fee_note: 'Delivery within Amsterdam €8, outside Amsterdam €10. If your postal code starts with 10xx or 11xx, it counts as Amsterdam.',
        total: 'Total',
        confirm_order: 'Confirm Order',
        success_title: 'Order Received!',
        success_message: 'Thank you for choosing Mezzesalade.',
        order_summary: 'Order Summary',
        new_order_btn: 'Create New Order',
        login_msg: 'Enter your phone number to see previous orders and auto-fill your info.',
        login_btn: 'Identify Me',
        previous_orders: 'Your Previous Orders',
        no_orders: 'You have no orders yet.',
        logout: 'Logout',
        identifying: 'Identifying...',
        optional: 'Optional',
        edit: 'Edit',
        update_order: 'Update Order',
        status_new: 'New',
        status_preparing: 'Preparing',
        status_ready: 'Ready',
        status_delivered: 'Delivered',
        cannot_edit: 'This order is being processed and cannot be edited anymore.',
        cancel: 'Cancel',
        shortcut_tip: '💡 Tip: Add this page to your home screen ("Add to Home Screen") to place orders quickly like an app.',
        get_directions: 'Get Directions',
        pickup_address_title: 'Pick-up Address',
        date_confirmation_note: 'Note: We will contact you to confirm our availability for the selected date.',
        filter_by_diet: 'Filter by Diet',
        diet_v: 'Vegan',
        diet_vg: 'Vegetarian',
        diet_gf: 'Gluten-Free',
        diet_n: 'Contains Nuts',
        order_overview: 'Order Overview',
        confirm_and_send: 'Confirm & Send',
        edit_order: 'Edit',
        added_to_cart: 'Added to cart!',
        admin_page: 'Admin Page',
        admin_management: 'Mezzesalade Management',
        ai_order: 'AI Order',
        new_order: 'New Order',
        all_orders: 'All Orders',
        revenue_report: 'Revenue Report',
        calendar: 'Calendar',
        daily_summary: 'Daily Summary',
        products: 'Products',
        customers: 'Customers',
        pending_orders: 'Pending Orders',
        see_all: 'See All',
        no_pending_orders: 'No pending orders',
        notifications: 'Notifications',
        no_notifications: 'No new notifications',
        items: 'items',
        preparing: 'Preparing',
        total_revenue: 'Total Revenue',
        today_orders: 'Today\'s Orders',
        total_orders: 'Total Orders',
        active_customers: 'Active Customers',
        order_details: 'Order Details',
        customer_details: 'Customer Details',
        order_status: 'Order Status',
        order_date_label: 'Order Date',
        last_updated: 'Last Updated',
        back_to_calendar: 'Back to Calendar',
        daily_summary_title: 'Daily Summary',
        shopping_list: 'Shopping List',
        by_products: 'By Products',
        by_category: 'By Category',
        total_items: 'Total Items',
        share_report: 'Share Report',
        share_menu: 'Share Menu',
        delete_confirmation: 'Are you sure?',
        save: 'Save',
        update: 'Update',
        days_short: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
        months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
        whatsapp_import: 'Import from WhatsApp',
        manual_order: 'Manual Order',
        product_summary: 'Product Summary',
        printable_summary: 'Printable Summary',
        today: 'Today',
        no_order_today: 'No orders for today',
        customer: 'Customer',
        recent_orders: 'Recent Orders',
        all: 'All',
        no_order_date: 'No orders on this date',
        order: 'Order',
        item: 'Item',
        search_placeholder: 'Search customer or order...',
        date_filter: 'Date Filter',
        status_filter: 'Status Filter',
        clear_filters: 'Clear Filters',
        no_orders_found: 'No orders found',
        date_all: 'All Time',
        date_today: 'Today',
        date_yesterday: 'Yesterday',
        date_this_week: 'This Week',
        date_last_week: 'Last Week',
        date_this_month: 'This Month',
        date_last_month: 'Last Month',
        date_last_3_months: 'Last 3 Months',
        date_this_year: 'This Year',
        date_last_year: 'Last Year',
        date_custom: 'Custom Date Range',
        start_date: 'Start Date',
        end_date: 'End Date',
        more: 'more...',
        customer_selection: 'Customer Selection',
        select_customer_btn: 'Select Customer',
        add_new_customer_btn: 'Add New Customer',
        add_product_btn: 'Add Product',
        order_items: 'Order Items',
        save_order: 'Save Order',
        no_items_in_order: 'No items added yet',
        choose_variation: 'Choose Variation',
        order_summary_title: 'Order Summary',
        edit_order_title: '✏️ Edit Order',
        new_order_title: '📝 New Order',
        change_btn: 'Change',
        delivery_address_label: '📍 Delivery Address',
        address_placeholder: 'Delivery address...',
        select_customer_placeholder: 'Select customer...',
        new_customer_title: 'New Customer',
        name_label: 'Name',
        phone_label: 'Phone',
        note_label: 'Note',
        name_placeholder: 'Customer name',
        search_product_placeholder: 'Search product...',
        search_results_title: 'Search Results',
        categories_title: 'Categories',
        saving_btn: '⏳ Saving...',
        unknown: 'Unknown',
        revenue_report_title: 'Revenue Report',
        today_total_revenue: "Today's Total Revenue",
        compared_to_yesterday: 'vs yesterday',
        pending_orders_count: 'Pending Orders',
        no_pending_orders: 'No pending orders',
        daily_revenues_title: 'Daily Revenues',
        today_label: 'Today',
        orders_count: 'orders',
        customers_title: '👥 Customers',
        new_btn: '+ New',
        search_customers_placeholder: 'Search customers...',
        no_customers_found: 'No customers found',
        add_first_customer: '+ Add First Customer',
        edit_customer_title: 'Edit Customer',
        email_label: 'Email',
        email_placeholder: 'example@email.com',
        delete_customer_confirm: 'Are you sure you want to delete this customer?',
        validation_name_phone: 'Name and phone are required!',
        ai_no_match: 'No matching products found. Please check product names.',
    },
    nl: {
        online_order: 'Online Bestellen',
        select_product: 'Product Selecteren',
        write_order: 'Bestellen via Tekst',
        ai_placeholder: 'Schrijf hier uw bestelling... bijv. 2 Linzensoep',
        add_to_list: 'Voeg toe aan lijst',
        cart: 'Uw Winkelmandje',
        delivery_method: 'Bezorgmethode',
        home_delivery: 'Thuisbezorging',
        outside: 'buiten',
        pickup: 'Afhalen',
        your_info: 'Uw Informatie',
        welcome_user: 'Welkom',
        full_name: 'Volledige Naam',
        phone_number: 'Telefoonnummer',
        address: 'Bezorgadres',
        order_date: 'Besteldatum',
        notes: 'Extra Notities',
        notes_placeholder: 'Allergieën of speciale verzoeken...',
        subtotal: 'Subtotaal',
        delivery_fee: 'Bezorgkosten',
        delivery_fee_note: 'Bezorging binnen Amsterdam €8, buiten Amsterdam €10. Als uw postcode begint met 10xx of 11xx, telt dit als Amsterdam.',
        total: 'Totaal',
        confirm_order: 'Bestelling Bevestigen',
        success_title: 'Bestelling Ontvangen!',
        success_message: 'Bedankt dat u voor Mezzesalade heeft gekozen.',
        order_summary: 'Bestelling Overzicht',
        new_order_btn: 'Nieuwe Bestelling Plaatsen',
        login_msg: 'Voer uw telefoonnummer in om eerdere bestellingen te zien en uw gegevens automatisch in te vullen.',
        login_btn: 'Identificeer Mij',
        previous_orders: 'Uw Vorige Bestelling',
        no_orders: 'U heeft nog geen bestellingen.',
        logout: 'Uitloggen',
        identifying: 'Identificeren...',
        optional: 'Optioneel',
        edit: 'Bewerken',
        update_order: 'Bestelling Bijwerken',
        status_new: 'Nieuw',
        status_preparing: 'Voorbereiden',
        status_ready: 'Gereed',
        status_delivered: 'Geleverd',
        cannot_edit: 'Deze bestelling wordt verwerkt ve kan niet meer worden bewerkt.',
        cancel: 'Annuleren',
        shortcut_tip: '💡 Tip: Voeg deze pagina toe aan uw beginscherm ("Zet op beginscherm") om snel bestellingen te plaatsen, net als bir app.',
        get_directions: 'Routebeschrijving',
        pickup_address_title: 'Afhaaladres',
        date_confirmation_note: 'Let op: We nemen contact met u op om onze beschikbaarheid voor de geselecteerde datum te bevestigen.',
        filter_by_diet: 'Filter op dieet',
        diet_v: 'Vegan',
        diet_vg: 'Vegetarisch',
        diet_gf: 'Glutenvrij',
        diet_n: 'Bevat noten',
        order_overview: 'Besteloverzicht',
        confirm_and_send: 'Bevestigen & Verzenden',
        edit_order: 'Bewerken',
        added_to_cart: 'Toegevoegd aan winkelwagen!',
        admin_page: 'Admin Pagina',
        admin_management: 'Mezzesalade Beheer',
        ai_order: 'AI Bestelling',
        new_order: 'Nieuwe Bestelling',
        all_orders: 'Alle Bestellingen',
        revenue_report: 'Omzetrapport',
        calendar: 'Kalender',
        daily_summary: 'Dagelijks Overzicht',
        products: 'Producten',
        customers: 'Klanten',
        pending_orders: 'Wachtende Bestellingen',
        see_all: 'Toon Alles',
        no_pending_orders: 'Geen wachtende bestellingen',
        notifications: 'Meldingen',
        no_notifications: 'Geen nieuwe meldingen',
        items: 'artikelen',
        preparing: 'Voorbereiden',
    }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
    const [lang, setLang] = useState(localStorage.getItem('lang') || 'tr');

    useEffect(() => {
        localStorage.setItem('lang', lang);
    }, [lang]);

    const t = (key) => {
        return translations[lang][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ lang, setLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    return useContext(LanguageContext);
}
